<?php
$translations = [
    'vi' => [
        'page_title' => 'Đăng ký tài khoản',
        'create_account' => 'Tạo tài khoản',
        'registration_successful' => 'Đăng ký thành công!',
        'please_save_credentials' => 'Tài khoản của bạn đã được tạo. Vui lòng lưu thông tin đăng nhập dưới đây.',
        'email_sent_success' => 'Thông tin đăng nhập đã được gửi đến email của bạn.',
        'could_not_send_email' => 'Chúng tôi không thể gửi email. Vui lòng lưu thông tin đăng nhập dưới đây.',
        'account_pending' => 'Tài khoản của bạn đang chờ xác minh bởi quản trị viên. Bạn cần đổi mật khẩu khi đăng nhập lần đầu.',
        'go_to_login' => 'Đi đến Đăng nhập',
        'already_have_account' => 'Đã có tài khoản?',
        'login_here' => 'Đăng nhập tại đây',

        'phone_number' => 'Số điện thoại',
        'email_address' => 'Địa chỉ email',
        'full_name' => 'Họ và tên',
        'date_of_birth' => 'Ngày sinh',
        'address' => 'Địa chỉ',
        'id_card_front' => 'Ảnh mặt trước CMND/CCCD',
        'id_card_back' => 'Ảnh mặt sau CMND/CCCD',
        'register' => 'Đăng ký',

        'phone_placeholder' => 'Ví dụ: 0901234567',
        'email_placeholder' => 'Ví dụ: user@example.com',
        'full_name_placeholder' => 'Ví dụ: Nguyễn Văn A',
        'address_placeholder' => 'Nhập địa chỉ đầy đủ của bạn',
        'front_help' => 'Tối đa 3 MB. Tối thiểu 900 x 600 px.',
        'back_help' => 'Tối đa 3 MB. Tối thiểu 900 x 600 px.',

        'phone_required' => 'Số điện thoại là bắt buộc.',
        'phone_format' => 'Số điện thoại phải từ 9-15 chữ số.',
        'phone_exists' => 'Số điện thoại này đã được đăng ký.',

        'login_title' => 'Đăng nhập - Ví Điện Tử',
        'e_wallet' => 'Ví Điện Tử',
        'sign_in_to_continue' => 'Đăng nhập để tiếp tục',
        'email_or_phone' => 'Email hoặc Số điện thoại',
        'password' => 'Mật khẩu',
        'enter_email_or_phone' => 'Nhập email hoặc số điện thoại',
        'enter_password' => 'Nhập mật khẩu',
        'login' => 'Đăng nhập',
        'remember_me' => 'Ghi nhớ đăng nhập',
        'forgot_password' => 'Quên mật khẩu?',
        'dont_have_account' => 'Chưa có tài khoản?',
        'register_here' => 'Đăng ký ngay',

        'please_enter_both' => 'Vui lòng nhập đầy đủ tên đăng nhập và mật khẩu.',
        'invalid_username_or_password' => 'Tên đăng nhập hoặc mật khẩu không đúng.',
        'account_disabled' => 'Tài khoản đã bị vô hiệu hóa, vui lòng liên hệ hotline 18001008.',
        'account_permanently_locked' => 'Tài khoản đã bị khóa do nhập sai mật khẩu nhiều lần, vui lòng liên hệ quản trị viên.',
        'account_temporarily_locked' => 'Tài khoản đang bị tạm khóa, vui lòng thử lại sau 1 phút.',

        // Notifications (user-facing)
        'notifications' => 'Thông báo',
        'your_notifications' => 'Thông báo của bạn',
        'no_notifications' => 'Chưa có thông báo nào.',
        'new_badge' => 'MỚI',
        'from' => 'Từ',
        'broadcast' => 'Thông báo chung',

        // Bug reports (user-facing)
        'report_bug'                 => 'Báo lỗi',
        'report_bug_intro'           => 'Bạn gặp sự cố hay điều gì đó khó hiểu? Hãy cho chúng tôi biết — chúng tôi sẽ kiểm tra và xử lý.',
        'bug_title_label'            => 'Tiêu đề ngắn gọn',
        'bug_description_label'      => 'Bạn đã gặp vấn đề gì?',
        'bug_description_help'       => 'Càng cụ thể càng tốt. Mô tả các bước thực hiện, thông báo lỗi và những gì bạn thấy trên màn hình.',
        'bug_send_to_dev'            => 'Gửi cho đội phát triển',
        'bug_thanks'                 => 'Cảm ơn bạn! Báo cáo của bạn đã được gửi đến đội ngũ kỹ thuật và sẽ được xử lý sớm nhất có thể.',
        'bug_report_another'         => 'Báo cáo lỗi khác',

        'dashboard_title' => 'Bảng điều khiển',
        'command_deck' => 'Bảng điều khiển',
        'welcome_user' => 'Chào mừng, %s!',
        'dashboard_intro' => 'Thông tin tài khoản và thao tác nhanh đã sẵn sàng bên dưới.',
        'dashboard_pending_notice' => 'Tài khoản của bạn đang <strong>chờ xác minh</strong>. Hầu hết tính năng chỉ khả dụng cho tài khoản đã xác minh.',
        'dashboard_update_notice' => 'Quản trị viên đã yêu cầu bổ sung thông tin.',
        'reupload_id_here' => 'Tải lại ảnh CMND/CCCD tại đây',
        'account_balance' => 'Số dư tài khoản',
        'account_status' => 'Trạng thái tài khoản',
        'profile' => 'Hồ sơ',
        'security' => 'Bảo mật',
        'quick_actions' => 'Thao tác nhanh',
        'deposit' => 'Nạp tiền',
        'withdraw' => 'Rút tiền',
        'transfer' => 'Chuyển tiền',
        'phone_card' => 'Thẻ điện thoại',
        'locked' => 'Khóa',
        'recent_activity' => 'Hoạt động gần đây',
        'sonar_log' => 'Nhật ký sonar của các biến động tài khoản gần nhất.',
        'fee' => 'Phí',
        'no_activity' => 'Chưa có hoạt động nào. Các giao dịch mới nhất sẽ xuất hiện tại đây.',
        'account_details' => 'Chi tiết tài khoản',
        'feature_verified_only' => 'Tính năng này chỉ khả dụng cho tài khoản đã xác minh.',
        'transfer_out' => 'Chuyển đi',
        'transfer_in' => 'Nhận tiền',
        'verified' => 'Đã xác minh',
        'pending_verification' => 'Chờ xác minh',
        'waiting_for_updates' => 'Chờ cập nhật',
        'disabled' => 'Đã vô hiệu hóa',

        'personal_information' => 'Thông tin cá nhân',
        'back_to_dashboard' => 'Quay lại bảng điều khiển',
        'profile_pending_notice' => 'Tài khoản của bạn đang chờ xác minh. Hầu hết tính năng ví sẽ bị hạn chế cho đến khi quản trị viên xác minh.',
        'profile_update_notice' => 'Quản trị viên đã yêu cầu bạn cập nhật thông tin.',
        'profile_disabled_notice' => 'Tài khoản của bạn đã bị vô hiệu hóa. Vui lòng liên hệ hỗ trợ.',
        'basic_information' => 'Thông tin cơ bản',
        'account_id' => 'Mã tài khoản',
        'role' => 'Vai trò',
        'member_since' => 'Tham gia từ',
        'last_updated' => 'Cập nhật lần cuối',
        'id_card' => 'CMND/CCCD',
        'front' => 'Mặt trước',
        'back' => 'Mặt sau',
        'not_uploaded' => 'Chưa tải lên',
        'no_id_uploaded' => 'Chưa có ảnh CMND/CCCD được tải lên.',
        'change_password' => 'Đổi mật khẩu',
        'transaction_history' => 'Lịch sử giao dịch',
        'user' => 'Người dùng',
    ],
    'en' => [
        'page_title' => 'Register',
        'create_account' => 'Create an Account',
        'registration_successful' => 'Registration Successful!',
        'please_save_credentials' => 'Your account has been created. Please save your login credentials below.',
        'email_sent_success' => 'Login credentials have been sent to your email.',
        'could_not_send_email' => 'We could not send an email. Please save your credentials from below.',
        'account_pending' => 'Your account is pending verification by the administrator. You will need to change your password on first login.',
        'go_to_login' => 'Go to Login',
        'already_have_account' => 'Already have an account?',
        'login_here' => 'Login here',

        'phone_number' => 'Phone Number',
        'email_address' => 'Email Address',
        'full_name' => 'Full Name',
        'date_of_birth' => 'Date of Birth',
        'address' => 'Address',
        'id_card_front' => 'ID Card - Front Photo',
        'id_card_back' => 'ID Card - Back Photo',
        'register' => 'Register',

        'phone_placeholder' => 'e.g. 0901234567',
        'email_placeholder' => 'e.g. user@example.com',
        'full_name_placeholder' => 'e.g. Nguyen Van A',
        'address_placeholder' => 'Enter your full address',
        'front_help' => 'Max 3 MB. Minimum 900 x 600 px.',
        'back_help' => 'Max 3 MB. Minimum 900 x 600 px.',

        'login_title' => 'Login - E-Wallet',
        'e_wallet' => 'E-Wallet',
        'sign_in_to_continue' => 'Sign in to continue',
        'email_or_phone' => 'Email or Phone Number',
        'password' => 'Password',
        'enter_email_or_phone' => 'Enter email or phone',
        'enter_password' => 'Enter your password',
        'login' => 'Login',
        'remember_me' => 'Remember me',
        'forgot_password' => 'Forgot password?',
        'dont_have_account' => "Don't have an account?",
        'register_here' => 'Register here',

        'please_enter_both' => 'Please enter both username and password.',
        'invalid_username_or_password' => 'Invalid username or password.',
        'account_disabled' => 'This account has been disabled, please contact the hotline 18001008.',
        'account_permanently_locked' => 'Account has been locked due to entering the wrong password many times, please contact the administrator.',
        'account_temporarily_locked' => 'Account is currently locked, please try again in 1 minute.',

        'dashboard_title' => 'Dashboard',
        'command_deck' => 'Command Deck',
        'welcome_user' => 'Welcome, %s!',
        'dashboard_intro' => 'Live account telemetry and quick actions are ready below.',
        'dashboard_pending_notice' => 'Your account is <strong>pending verification</strong>. Most features are only available for verified accounts.',
        'dashboard_update_notice' => 'An admin has requested additional information.',
        'reupload_id_here' => 'Re-upload your ID card photos here',
        'account_balance' => 'Account Balance',
        'account_status' => 'Account Status',
        'profile' => 'Profile',
        'security' => 'Security',
        'quick_actions' => 'Quick Actions',
        'deposit' => 'Deposit',
        'withdraw' => 'Withdraw',
        'transfer' => 'Transfer',
        'phone_card' => 'Phone Card',
        'locked' => 'Locked',
        'recent_activity' => 'Recent Activity',
        'sonar_log' => 'Sonar log of your latest account movement.',
        'fee' => 'Fee',
        'no_activity' => 'No activity detected yet. Your latest transactions will appear here.',
        'account_details' => 'Account Details',
        'feature_verified_only' => 'This feature is only available for verified accounts.',
        'transfer_out' => 'Transfer Out',
        'transfer_in' => 'Transfer In',
        'verified' => 'Verified',
        'pending_verification' => 'Pending Verification',
        'waiting_for_updates' => 'Waiting for Updates',
        'disabled' => 'Disabled',

        'personal_information' => 'Personal Information',
        'back_to_dashboard' => 'Back to Dashboard',
        'profile_pending_notice' => 'Your account is pending verification. Most wallet features are restricted until an admin verifies your account.',
        'profile_update_notice' => 'An admin has requested updates to your information.',
        'profile_disabled_notice' => 'Your account has been disabled. Please contact support.',
        'basic_information' => 'Basic Information',
        'account_id' => 'Account ID',
        'role' => 'Role',
        'member_since' => 'Member Since',
        'last_updated' => 'Last Updated',
        'id_card' => 'ID Card',
        'front' => 'Front',
        'back' => 'Back',
        'not_uploaded' => 'Not uploaded',
        'no_id_uploaded' => 'No ID card images uploaded.',
        'change_password' => 'Change Password',
        'transaction_history' => 'Transaction History',
        'user' => 'User',

        // Bug reports (user-facing)
        'report_bug'                 => 'Report a bug',
        'report_bug_intro'           => "Found something broken or confusing? Tell us what you saw and we'll get it fixed.",
        'bug_title_label'            => 'Short title',
        'bug_description_label'      => 'What happened?',
        'bug_description_help'       => 'Be specific. Include steps to reproduce, error messages, and what you saw on screen.',
        'bug_send_to_dev'            => 'Send to dev team',
        'bug_thanks'                 => "Thanks! Your report is in the dev queue. We'll look at it as soon as we can.",
        'bug_report_another'         => 'Report another',
    ],
];

if (isset($_GET['lang']) && in_array($_GET['lang'], ['vi', 'en'], true)) {
    $_SESSION['lang'] = $_GET['lang'];
}

$lang = $_SESSION['lang'] ?? 'vi';

function __($key) {
    global $translations, $lang;
    return $translations[$lang][$key] ?? $key;
}
